### ISSUE TITLE
Message not showing without refresh.

### ISSUE THREAD

**Issue by Hateem76** [pusher/laravel-chat#2]
I opened two windows, one in my chrome normal tab and other in incognito tab to check messages. But it gets the other person's sent message after refresh.

**Comment by benw-pusher** [comment]
This is likely to be an environmental or implementation issue. 
Do you see the messages shown correctly in the Pusher Debug Console (available in the dashboard)? 
The fact the messages are available after refresh indicates the messages are being stored correctly, so it is likely either the broadcast of the messages or the handling of the message on the client that is not working.

**Comment by Hateem76** [comment]
> This is likely to be an environmental or implementation issue. Do you see the messages shown correctly in the Pusher Debug Console (available in the dashboard)? The fact the messages are available after refresh indicates the messages are being stored correctly, so it is likely either the broadcast of the messages or the handling of the message on the client that is not working.

When i send message, it gives me 500(internal server error on /messages address in console. i.e. the message is not broadcasting, but it is getting stored in db, you are right. Any suggestion?

**Comment by benw-pusher** [comment]
Can you share the full error message?

**Comment by Hateem76** [comment]
message: "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api-ap1.pusher.com/apps/1306522/events?auth_key=26fbf90c1d54ac7cca4f&auth_timestamp=1637934166&auth_version=1.0&body_md5=4b220ebc0370215cd37557955d565c65&auth_signature=3210612ff25990b443b2e0937881fb2c0d6c0640d41c9b5b33479d2691bf55a5"

**Comment by benw-pusher** [comment]
This is because your servers CA certificate store is not up to date. Here's a relevant SO answer:
https://stackoverflow.com/a/31830614

I've copied it in here for your convenience:

1. Download the latest cacert.pem from https://curl.haxx.se/ca/cacert.pem
2. Add the following line to php.ini: (if this is shared hosting and you don't have access to php.ini then you could add this to .user.ini in public_html).

curl.cainfo="/path/to/downloaded/cacert.pem"
Make sure you enclose the path within double quotation marks!!!

You are experiencing this because this library now defaults to using TLS. You can disable this behaviour by setting 'useTLS' => false in the options, as described in the README:

https://github.com/pusher/pusher-http-php#pusher-channels-constructor

**Comment by benw-pusher** [comment]
I'll close this with the above solution, however if you continue to encounter errors please do get in touch with us.
